spring:
  application:
    name: naming-server

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761

