name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build Eureka Naming Server Docker Image
        working-directory: naming-server
        run: |
          mvn spring-boot:build-image -DskipTests 

      - name: Build API Gateway Docker Image
        working-directory: api-gateway
        run: |
          mvn spring-boot:build-image -DskipTests 

      - name: Build Exchange Service Docker Image
        working-directory: exchange-service
        run: |
          mvn clean package -DskipTests

      - name: Build Book Service Docker Image
        working-directory: book-service
        run: |
          mvn clean package -DskipTests

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:${{ github.RUN_ID }}

          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.RUN_ID }}

          docker push ${{ secrets.DOCKER_USERNAME }}/exchange-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/exchange-service:${{ github.RUN_ID }}

          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:${{ github.RUN_ID }}

      - name: Push Docker Images to Docker Hub
        run: |
          ${{ secrets.DOCKER_USERNAME }}/$image:latest
          ${{ secrets.DOCKER_USERNAME }}/$image:${{ github.RUN_ID }}